server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/caigou?allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userService
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis:
  type-aliases-package: com.chen.user.entiy
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.chen: debug