server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.1:3306/crm?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: wusihao.@123
userinfo:
  name: Angus
  age: 22
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml