server:
  port: 8080
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: eureka8080
