server:
  port: 18082
spring:
  datasource:
    url: jdbc:mysql:///crm?serverTimezone=GMT%2B8&characterEncoding=utf-8&&allowMultiQueries=true
    username: root
    password: wusihao.@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  redis:
    host: localhost
    port: 6379
#  level:
#    com: debug
mybatis-plus:
  mapper-locations: classpath:mybatis/*/*Mapper.xml

#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB