server:
  port: 9091 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:
        server-addr: localhost:8848
        namespace: 418ec664-d92e-4cd8-a3d4-c6e8565a55f5
    gateway:
      routes: # 网关路由配置规则  集合
        - id: basics-service # 路由id，自定义，只要唯一即可
          #        uri: http://127.0.0.1:8081 # 静态路由 路由的目标地址 http就是固定地址
          uri: lb://basics # 动态路由 路由的目标地址(http://localhost:8081/) lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件 可以设置多个断言
            - Path=/metadata/**,/subClass/**,/legalPerson/** ,/partner/**,/plan/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: inquiry-service # 路由id，自定义，只要唯一即可
          #        uri: http://127.0.0.1:8081 # 静态路由 路由的目标地址 http就是固定地址
          uri: lb://inquiry # 动态路由 路由的目标地址(http://localhost:8081/) lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件 可以设置多个断言
            - Path=/inquiryList/**, # 这个是按照路径匹配，只要以/user/开头就符合要求
            #          - Before=2024-11-29T17:42:47.789-07:00[Asia/Shanghai] #是否符合时间条件
            #        filters: #路由过滤器设置  可以设置一组过滤规则
            #          - AddRequestHeader=Header,hello world! #添加请求头  1

            #        - id: order-service # 路由id，自定义，只要唯一即可
            #          #        uri: http://127.0.0.1:8082 # 路由的目标地址(http://localhost:8082) http就是固定地址
            #          uri: lb://orderService
            #          predicates:
            #            - Path=/order/**
            #          - Before=2022-11-29T17:42:47.789-07:00[Asia/Shanghai]
            #      default-filters:  #默认过滤器
            #        - AddRequestHeader=Truth,hello world! 1
            #        - ARequestHeader=Truth,hello world! 2

            # gateway的全局跨域请求配置
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods: "*"
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary, RETAIN_UNIQUE